### PR TITLE
Fixed TestScene

### PR DESCRIPTION
**Pull request by dhallstr**
I fixed the movement issues and the crash on right-clicking in testScene.

### CODE REVIEW

**Review by smilewood — APPROVED** [review]
Looks good.

**Review by habeeb-umo — APPROVED** [review]
Looks good, @dhallstr just don't merge it yet in case there are merge conflicts with @MystikalPooka 's changes. Thanks!

**Comment by smilewood** [comment]
There should not merge conflicts: @MystikalPooka did not modify TestScene and this patch did not modify LevelGenScene

**Review by MystikalPooka — APPROVED** [review]
I'm okay with merging this if need be. This scene doesn't have any conflicts with anything I have been working on for sure.

**Pull request merged**
