### PR TITLE
Dhallstr branch

### PR DESCRIPTION
**Pull request by habeeb-umo**
Creating PR for @dhallstr

### CODE REVIEW

**Comment by habeeb-umo** [comment]
@dhallstr Code looks good as a simple way to move the player. 

I would say that the player object needs a rigid body with the X axis frozen. 

Also, when the player object runs into something, the camera keeps running. See if you can find a way to lock the camera onto the player object unconditionally. 

Good job on nailing the perspective and setting up the scene!

**Review by smilewood — APPROVED** [review]
@dhallstr Nicely done with the scene; this looks like exactly like what we will need to start the rest of the process.
On the note of the code, the one thing that I noticed that should be added to movement code in the future is a `Time.deltaTime` to make sure that movement feels the same speed no matter the speed the game is running at. The only change it would need in this code is something like:
`transform.position = new Vector3(transform.position.x + xOffset * speed * Time.deltaTime, transform.position.y, transform.position.z + yOffset * speed * Time.deltaTime);
`
Not necessary for this test, but something to keep in mind for the future.

**Review by MystikalPooka — APPROVED** [review]
Looks great! Next up is to add simple colliders.

**Review by MystikalPooka — CHANGES_REQUESTED** [review]
Looks like the scripts got moved from Assets/Scripts to ./Scripts, while keeping the assets folder scripts intact.

**Comment by dhallstr** [comment]
You are correct. Sorry about that! How can I change it?

**Comment by MystikalPooka** [comment]
Will re-upload and request new review on pushing new branch. Fixing directory structure.

**Pull request closed without merging**
