### PR TITLE
Added navmesh and pathfinding on click

### PR DESCRIPTION
**Pull request by MystikalPooka**
Added pathfinding nav mesh agent to player model and baked in nav mesh to the scene.

MUST BAKE A NEW NAV MSH FOR EVERY NEW SCENE. (it is really easy to do... and might be able to do this dynamically on generated maps.... hopefully... maybe?)

TODO: Test with dynamic maps. Probably breaks this (for now)

--ALSO commented out some potentially unneeded code. If these are needed, uncomment as needed, otherwise delete in next patch. @dhallstr @JonathanGriego

### CODE REVIEW

**Comment by habeeb-umo** [comment]
#45

**Review by smilewood — APPROVED** [review]
Looks good. It also seems to have fixed the spring-back bug. I like that the hold mouse button moment uses the pathfinding.

**Comment by MystikalPooka** [comment]
#25 - Should fix this as well

**Review by dhallstr — APPROVED** [review]
Looks good!

**Review by habeeb-umo — APPROVED** [review]
Real smooth. good job!

**Pull request merged**
