### PR TITLE
Dhallstr mouse motion patch3

### PR DESCRIPTION
**Pull request by dhallstr**

### CODE REVIEW

**Comment by dhallstr** [comment]
Fixed #22

**Review by smilewood — APPROVED** [review]
Looks good. Glad that everything is pulling together, and mouse movement works continuously. 
With the collisions, in the future we may want to look into a way to stop the character from attempting to move when it is walking into a wall, as is it sits there and jitters.

**Comment by dhallstr** [comment]
That shouldn't be a problem when we get path finding working.

**Comment by smilewood** [comment]
it isn't for the menu (go here) movement, but if we let the player drive the way this works if you hold the mouse then it may be noticeable. Future problem, but something I noticed.

**Review by MystikalPooka — APPROVED** [review]
Looks good!

**Pull request merged**
