### PR TITLE
Jgriego-Patch1-TapToMove

### PR DESCRIPTION
**Pull request by JonathanGriego**
Added a script called TapToMove to the game object  'Model'; this allows the object to be moved by clicking with the mouse on a solid object in the game field. Movement speed can be adjusted in Unity by adjusting the 'duration' field of the script attached to 'Model'. 

Credit for the code in TapToMove goes to Sujit Horakeri; http://www.thegamecontriver.com/2014/10/move-to-mouse-click-touch-position-unity.html

Also added a physics -> rigid body component to 'Model' that makes it obey physics; i.e. it will fall over when unbalanced and will not be able to pass through other physical objects in the game field.

### CODE REVIEW

**Comment by JonathanGriego** [comment]
One last note this code also supports touchscreens in addition to mouse input.

**Comment by smilewood** [comment]
So it looks to me like you did not get this uploaded correctly, I am not seeing any additional scripts, and you seem to have moved the scene out of the assets folder and into the root folder. You will need to make sure that you upload the entire assets folder that you are working from in order to make sure we get all of the data.

**Comment by smilewood** [comment]
On the note of the code, did you utilize the mouse location finding that @dhallstr worked out or write your own? If you didn't see his, make sure you are working off the most updated version of the master branch.

**Comment by dhallstr** [comment]
Motion code should all be associated with the Player object, not the Model object. That way the camera will remain centered on the model.

**Comment by JonathanGriego** [comment]
I did not use @dhallstr code; I am still pretty new to coding and I could not figure out how to take the next step in his code so I ended up using someone else's code that I understood better.

**Comment by dhallstr** [comment]
Just write an event listener function in whatever script you've made like so:
```
public void onMouseButtonDown(int button, Vector3 pos, Transform object) {
    /* Handle mouse down event here (note that mouseButtonDown calls once when the user first presses
 the mouse button. If you want the event called for each frame the button is held, just use the 
mouseButton function. The button parameter will be 0 for left click, 1 for right click, so you're probably 
just going to want to check for a 0. pos will be (x,y,z) coords of location the user clicked, but the y coord
 will always be 0. object is the gameobject the user clicked. You don't need to worry about that; I just 
thought it might be useful later when determining whether the user clicked an enemy or the ground 
near the enemy. */
}
```
Then, after you attach your script to an object, go to the Input object, click the "+" button on the appropriate event, and then configure the event to call your function by selecting the object and the method you created.

**Pull request closed without merging**
