### PR TITLE
Jgriego-Patch2-TapToMove

### PR DESCRIPTION
**Pull request by JonathanGriego**
Trying to upload whole assets folder

### CODE REVIEW

**Comment by JonathanGriego** [comment]
I think I uploaded the whole assets folder, let me  know if it worked.

edit: if it did work I attached the script to the 'player'... set? instead of the 'Model' this time.

**Comment by smilewood** [comment]
It worked. checking it out now

**Comment by smilewood** [comment]
Nicely done getting the movement to be linked to the mouse. I also like the transitioning for desktop and mobile input, even if that isn't out top priority it could be good to lay the groundwork.  I do think that it would be more beneficial to the project long term if you were able to figure out how to link the movement to the mouse input attached to the input object, this would allow us to have mouse events that did not cause the player to move in the future. Take a look at the comments that @dhallstr  left on your last pull request (#19)  and use parts of the code that you came up with for this branch to figure that out.  
I think, after just a glance at it, that line 59 of your TapToMove would be a good place to start from, the `Vector3.Lerp` function is a great thing to move an object from one place to another. 

ps. if you do update it, start from this branch, it will keep you from having to start from main again.

**Comment by habeeb-umo** [comment]
Beautifully done, @JonathanGriego. Just see if you can incorporate these changes with @dhallstr's code, or @dhallstr, see if you can do that. bravo!

**Comment by JonathanGriego** [comment]
I cant figure out what the conflicts are that are keeping this from being merged. Thoughts?

**Comment by smilewood** [comment]
It looks like the conflict is coming from this branch being behind master because of the menu stuff I added. Your ranch seems to want to change Scene1.unity to remove the gameobjects that I added. I am not entirely sure how to resolve this from the web, but if you like I can try when I get home.

**Review by smilewood — APPROVED** [review]
Ok, I fixed the merge conflict, and made sure that it was working. Looks good to merge. 
You should take a look sometime at linking the movement in with the mouseListerer and the popup menu system, or we can look at that at the meeting tomorrow.

**Pull request merged**
